### ISSUE TITLE
fork moved from gevent.hub to gevent.os

### ISSUE THREAD

**Issue by apatrushev** [benoitc/tproxy#13]
``` python
Traceback (most recent call last):
  File "/venv/bin/tproxy", line 7, in <module>
    from tproxy.app import run
  File "/venv/lib/python2.7/site-packages/tproxy/app.py", line 19, in <module>
    from . import util
  File "/venv/lib/python2.7/site-packages/tproxy/util.py", line 23, in <module>
    from gevent.hub import fork
ImportError: cannot import name fork
```

**Comment by apatrushev** [comment]
util.py already contains required changes, but was not released yet  - version installed from pypi is unusable

**Comment by benoitc** [comment]
so why closing the ticket? Would it be solved by a new release?

**Comment by apatrushev** [comment]
> Would it be solved by a new release?

Definitely. It was fixed by #6.

UPDATE: But there are other problems with current pypi version, which was already solved in some forks.
